config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'playbooks#index'

  resources :playbooks, except: [:index] do
    resources :steps, except: [:destroy, :update]
    resources :plays, except: [:destroy, :update]
  end
  resources :steps, only: [:destroy, :update]
  resources :plays, only: [:destroy, :update] do
    member do
      put :next_step
      put :finish
    end
    resources :play_step_comments, except: [:show, :destroy, :update]
  end
  resources :play_step_comments, only: [:destroy, :update]
end

app/models/play.rb
class Play < ApplicationRecord
  STEP_STATUSES = %w[skipped failed done].freeze

  validates :title, presence: true, allow_blank: false
  validate :validate_steps_presence, on: :create
  validate :validate_current_step, on: :update

  enum :status, {
    running:   1,
    abandoned: 2,
    done:      3,
    failed:    4,
  }

  belongs_to :playbook
  has_many :play_step_comments, dependent: :destroy

  before_create :fill_metadata

  def next!(status: nil)
    prevent_changes!

    index = steps_data.find_index { |d| d['id'] == current_step_id }
    raise ActiveRecord::RecordNotFound, "No step found in current play with id #{current_step_id}" unless index

    next_or_finish! current_step_index: index, current_step_status: status
  end

  def finish!(status: nil)
    prevent_changes!

    skip_remaining
    update! status:   status || Play.statuses[:done],
            ended_at: Time.zone.now
  end

  def considered_done?
    !running?
  end

  def contains_step?(id)
    steps_data.find_index { |d| d['id'] == id }.present?
  end

  private

  def next_or_finish!(current_step_index:, current_step_status: nil)
    steps_data[current_step_index]['status'] = current_step_status.presence || 'done'

    next_step = steps_data[current_step_index + 1]
    if next_step
      self.current_step_id = next_step['id']
      save!
    elsif current_step_index + 1 == steps_data.count
      finish!
    end
  end

  def skip_remaining
    index = steps_data.find_index { |d| d['id'] == current_step_id }

    loop do
      step = steps_data[index]
      break unless step

      step['status'] = 'skipped' if step
      index += 1
    end
  end

  def prevent_changes!
    raise 'Play is considered done and cannot be changed' if considered_done?
  end

  def validate_steps_presence
    errors.add :playbook, 'has no steps' unless playbook&.steps&.count&.positive?
  end

  def validate_current_step
    errors.add :current_step, 'does not exist in steps list' unless steps_data.find_index { |d| d['id'] == current_step_id }
  end

  def fill_metadata # rubocop:disable Metrics/AbcSize
    raise 'Cannot fill metadata on existing plays' if persisted?

    steps_list = playbook.steps.order(position: :asc)

    self.playbook_data   = { name: playbook.name, description: playbook.description, version: playbook.updated_at }
    self.steps_data      = steps_list.map { |step| { id: step.id, name: step.name, content: step.content, position: step.position, version: step.updated_at, status: '' } }
    self.current_step_id = steps_list.first.id
    self.status          = Play.statuses[:running]
    self.started_at      = Time.zone.now
  end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :set_playbook, only: [:index, :show, :create]
  before_action :set_play, only: [:show, :edit, :update, :destroy, :next_step, :finish]

  # GET /plays or /plays.json
  def index
    @plays = policy_scope(Play).where(playbook: @playbook)
  end

  # GET /plays/1 or /plays/1.json
  def show; end

  # GET /plays/new
  def new
    @play = Play.new
  end

  # GET /plays/1/edit
  def edit; end

  # POST /plays or /plays.json
  def create # rubocop:disable Metrics/AbcSize
    @play = Play.new(play_params)
    @play.playbook = @playbook

    respond_to do |format|
      if @play.save
        format.html { redirect_to playbook_play_url(@play.playbook, @play), notice: I18n.t('controller.play.create.success') }
        format.json { render :show, status: :created, location: @play }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plays/1 or /plays/1.json
  def update
    respond_to do |format|
      if @play.update(play_params)
        format.html { redirect_to playbook_play_url(@play.playbook, @play), notice: I18n.t('controller.play.update.success') }
        format.json { render :show, status: :ok, location: @play }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  def next_step
    respond_to do |format|
      if @play.next! status: params[:status]
        format.html { redirect_to playbook_play_url(@play.playbook, @play), notice: I18n.t('controller.play.update.success') }
        format.json { render :show, status: :ok, location: @play }
      end
    end
  end

  def finish
    respond_to do |format|
      if @play.finish! status: params[:status]
        format.html { redirect_to playbook_play_url(@play.playbook, @play), notice: I18n.t('controller.play.update.success') }
        format.json { render :show, status: :ok, location: @play }
      end
    end
  end

  # DELETE /plays/1 or /plays/1.json
  def destroy
    @play.destroy!

    respond_to do |format|
      format.html { redirect_to playbook_url(@play.playbook), notice: I18n.t('controller.play.destroy.success') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_play
    @play = Play.find(params[:id])

    authorize @play
  end

  def set_playbook
    @playbook = Playbook.find(params[:playbook_id])

    authorize @playbook
  end

  # Only allow a list of trusted parameters through.
  def play_params
    params.require(:play).permit(:title, :description)
  end
end

app/views/plays/_form.html.erb
<% form_url = play.id ? play_url(play) : playbook_plays_url(playbook_id: params[:playbook_id]) %>
<%= form_with(model: play, url: form_url) do |form| %>
  <% if play.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(play.errors.count, 'error') %> prohibited this play from being saved:</h2>

      <ul>
        <% play.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: 'display: block' %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: 'display: block' %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/plays/_play.html.erb
<div id="<%= dom_id play %>">
  <p>
    <strong>Title:</strong>
    <%= play.title %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= play.status %>
  </p>

  <p>
    <strong>Started at:</strong>
    <%= play.started_at %>
  </p>

  <p>
    <strong>Ended at:</strong>
    <%= play.ended_at || '-' %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= play.description %>
  </p>

  <% unless play.considered_done? %>
    <%= button_to 'Finish run', finish_play_url(play), method: :put %>
    <%= button_to 'Fail run', finish_play_url(play, params: { status: 'failed' }), method: :put %>
    <%= button_to 'Abandon run', finish_play_url(play, params: { status: 'abandoned' }), method: :put %>
  <% end %>
</div>

app/views/plays/_playbook.html.erb
<p>
  <strong>Name:</strong>
  <%= link_to play.playbook.name, playbook_url(play.playbook) %>
  <% if play.playbook.name != play.playbook_data['name'] %>
    <em>(<%= play.playbook_data['name'] %>)</em>
  <% end %>
</p>

<p>
  <strong>Version</strong>
  <%= play.playbook_data['version'] %>
</p>

<p>
  <strong>Description</strong>
  <%= play.playbook_data['content'] %>
</p>

app/views/plays/_steps.html.erb
<%
play.steps_data.each do |step|
  is_current_step = step['id'] == play.current_step_id
%>
  <details <%= is_current_step ? 'open="open"' : '' %>>
    <summary>
      <% if is_current_step %>
        <strong>[Current]</strong>
      <% end %>
      <% if step['status'] %>
        <strong><%= step['status'] %></strong>
      <% end %>
      #<%= step['position'] %> <%= step['name'] %>

      <% if is_current_step && !play.considered_done? %>
        <%= button_to 'Next', next_step_play_url(play_id: play.id), method: :put %>
        <%= button_to 'Skip', next_step_play_url(play_id: play.id, params: { status: 'skipped' }), method: :put %>
        <%= button_to 'Fail', next_step_play_url(play_id: play.id, params: { status: 'failed' }), method: :put %>
      <% end %>
    </summary>

    <div>
      <%= step['content'] %>
    </div>

    <h3>Comments</h3>
    <%= render 'play_step_comments/list', play_step_comments: play.play_step_comments.select { |c| c.step_id == step['id'] } %>
    <%= render 'play_step_comments/form', play_step_comment: PlayStepComment.new(play: play, step_id: step['id']) %>
  </details>
<% end %>

app/views/plays/edit.html.erb
<h1>Editing play</h1>

<%= render 'form', play: @play %>

<br>

<div>
  <%= link_to 'Show this play', playbook_play_url(@play.playbook, @play) %> |
  <%= link_to 'Back to plays', playbook_plays_path(@play.playbook) %>
</div>

app/views/plays/index.html.erb
<h1>Plays</h1>
<p>For playbook: <%= link_to @playbook.name, playbook_url(@playbook) %></p>

<div id="plays">
  <% @plays.each do |play| %>
    <%= render play %>
    <p>
      <%= link_to 'Show this play', playbook_play_url(play.playbook, play) %>
    </p>
  <% end %>
</div>

<%= link_to 'New play', new_playbook_play_path %>

app/views/plays/new.html.erb
<h1>New play</h1>

<%= render 'form', play: @play %>

<br>

<div>
  <%= link_to 'Back to plays', playbook_plays_path(playbook_id: params[:playbook_id]) %>
</div>

app/views/plays/show.html.erb
<%= render @play %>

<h2>Playbook</h2>

<%= render 'plays/playbook', play: @play %>

<h2>Steps</h2>

<%= render 'plays/steps', play: @play %>

<div>
  <%= link_to 'Edit this play', edit_playbook_play_path(@play.playbook, @play) %> |
  <%= link_to 'Back to plays', playbook_plays_path(@play.playbook) %>

  <%= button_to 'Destroy this play', @play, method: :delete %>
</div>