config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'playbooks#index'

  resources :playbooks, except: [:index] do
    resources :steps, except: [:destroy, :update]
    resources :plays, except: [:destroy, :update]
  end
  resources :steps, only: [:destroy, :update]
  resources :plays, only: [:destroy, :update] do
    member do
      put :next_step
      put :finish
    end
    resources :play_step_comments, except: [:show, :destroy, :update]
  end
  resources :play_step_comments, only: [:destroy, :update]
end

app/models/play_step_comment.rb
class PlayStepComment < ApplicationRecord
  validates :content, presence: true, allow_blank: false
  validates :step_id, presence: true, allow_blank: false
  validate :validate_step_presence

  belongs_to :play

  private

  def validate_step_presence
    return if step_id.blank?

    errors.add :step, 'does not exist in current play' unless play.contains_step? step_id
  end
end

app/controllers/play_step_comments_controller.rb
class PlayStepCommentsController < ApplicationController
  before_action :set_play, only: [:index, :create]
  before_action :set_play_step_comment, only: [:edit, :update, :destroy]

  # GET /play_step_comments or /play_step_comments.json
  def index
    @play_step_comments = policy_scope(PlayStepComment).where(play: @play)
  end

  # GET /play_step_comments/new
  def new
    @play_step_comment = PlayStepComment.new play_id: params[:play_id]
  end

  # GET /play_step_comments/1/edit
  def edit; end

  # POST /play_step_comments or /play_step_comments.json
  def create # rubocop:disable Metrics/AbcSize
    @play_step_comment = PlayStepComment.new(play_step_comment_params)
    @play_step_comment.play = @play

    respond_to do |format|
      if @play_step_comment.save
        format.html { redirect_to playbook_play_url(@play.playbook, @play), notice: I18n.t('controller.play_step_comment.create.success') }
        format.json { render :show, status: :created, location: @play_step_comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @play_step_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /play_step_comments/1 or /play_step_comments/1.json
  def update # rubocop:disable Metrics/AbcSize
    respond_to do |format|
      if @play_step_comment.update(play_step_comment_params)
        format.html { redirect_to playbook_play_url(@play_step_comment.play.playbook_id, @play_step_comment.play), notice: I18n.t('controller.play_step_comment.update.success') }
        format.json { render :show, status: :ok, location: @play_step_comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @play_step_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /play_step_comments/1 or /play_step_comments/1.json
  def destroy
    @play_step_comment.destroy!

    respond_to do |format|
      format.html { redirect_to playbook_play_url(@play_step_comment.play.playbook, @play_step_comment.play), notice: I18n.t('controller.play_step_comment.destroy.success') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_play_step_comment
    @play_step_comment = PlayStepComment.find(params[:id])

    authorize @play_step_comment
  end

  def set_play
    @play = Play.find(params[:play_id])

    authorize @play
  end

  # Only allow a list of trusted parameters through.
  def play_step_comment_params
    params.require(:play_step_comment).permit(:step_id, :content)
  end
end

app/views/play_step_comments/_form.html.erb
<% form_url = play_step_comment.id ? play_step_comment_url(play_step_comment) : play_play_step_comments_url(play_step_comment.play) %>
<%= form_with(model: play_step_comment, url: form_url) do |form| %>
  <% if play_step_comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(play_step_comment.errors.count, 'error') %> prohibited this play_step_comment from being saved:</h2>

      <ul>
        <% play_step_comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if play_step_comment.step_id.blank? %>
    <div>
      <%= form.label :step_id, style: 'display: block' %>
      <%= form.number_field :step_id %>
    </div>
  <% else %>
    <%= form.hidden_field :step_id %>
  <% end %>

  <div>
    <%= form.label :content, style: 'display: block' %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/play_step_comments/_list.html.erb
<div id="play_step_comments">
  <% play_step_comments.each do |play_step_comment| %>
    <%= render play_step_comment %>
    <p>
      <%= link_to 'Edit', edit_play_play_step_comment_url(play_step_comment.play_id, play_step_comment) %>
      <%= button_to 'Destroy', play_step_comment_url(play_step_comment), method: :delete %>
    </p>
  <% end %>
</div>

app/views/play_step_comments/_play_step_comment.html.erb
<div id="<%= dom_id play_step_comment %>">
  <p>
    <strong>Play:</strong>
    <%= play_step_comment.play_id %>
  </p>

  <p>
    <strong>Step:</strong>
    <%= play_step_comment.step_id %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= play_step_comment.content %>
  </p>

</div>

app/views/play_step_comments/edit.html.erb
<h1>Editing play step comment</h1>

<%= render 'form', play_step_comment: @play_step_comment %>

<br>

<div>
  <%= link_to 'Back to play', playbook_play_url(@play_step_comment.play.playbook_id, @play_step_comment.play.id) %>
</div>

app/views/play_step_comments/index.html.erb
<h1>Play step comments</h1>

<%= render 'list', play_step_comments: @play_step_comments %>

<%= link_to 'New play step comment', new_play_play_step_comment_path(play_id: params[:play_id]) %>

app/views/play_step_comments/new.html.erb
<h1>New play step comment</h1>

<%= render 'form', play_step_comment: @play_step_comment %>

<br>

<div>
  <%= link_to 'Back to play step comments', play_play_step_comments_path(params[:play_id]) %>
</div>

app/views/play_step_comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @play_step_comment %>

<div>
  <%= link_to 'Edit this play step comment', edit_play_step_comment_path(@play_step_comment) %> |
  <%= link_to 'Back to play step comments', play_step_comments_path %>

  <%= button_to 'Destroy this play step comment', @play_step_comment, method: :delete %>
</div>