config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'playbooks#index'

  resources :playbooks, except: [:index] do
    resources :steps, except: [:destroy, :update]
    resources :plays, except: [:destroy, :update]
  end
  resources :steps, only: [:destroy, :update]
  resources :plays, only: [:destroy, :update] do
    member do
      put :next_step
      put :finish
    end
    resources :play_step_comments, except: [:show, :destroy, :update]
  end
  resources :play_step_comments, only: [:destroy, :update]
end

app/models/step.rb
class Step < ApplicationRecord
  validates :name, presence: true, allow_blank: false

  belongs_to :playbook

  before_validation :initialize_position, unless: :persisted?
  after_create :apply_position
  after_update :apply_position, if: :position_previously_changed?

  # Updates the other steps position
  #
  # @param to [Integer] Where to place the step. Step with same position will be placed _after_ this step.
  # @param in_hook [Boolean] Whether to also update the step's position. This is only here to ease executions
  #                          in hooks, when the new position is already saved, and should be left as-is in most
  #                          of the cases
  def move!(to:, in_hook: false) # rubocop:disable Metrics/AbcSize
    raise 'Cannot move without a playbook' unless playbook

    # When in hooks (create/update), final position is already set, so we do as if the step was moved from the end of the list
    from = in_hook && position == to ? playbook.steps.count + 1 : position
    selector = from < to ? 'position > ? AND position <= ?' : 'position < ? AND position >= ?'
    change   = from < to ? 'position = position - 1' : 'position = position + 1'

    transaction do
      playbook.steps.where.not(id: id).where(selector, from, to).update_all change # rubocop:disable Rails/SkipsModelValidations
      update_column :position, to unless in_hook # rubocop:disable Rails/SkipsModelValidations
    end
  end

  def self.fix_positions!
    Playbook.find_each do |playbook|
      transaction do
        playbook.steps.order(:position).each_with_index do |step, i|
          step.update_column :position, i # rubocop:disable Rails/SkipsModelValidations
        end
      end
    end
  end

  private

  # Changes position on other steps without updating self position
  def apply_position
    move! to: position, in_hook: true
  end

  # Determines initial position in the playbook
  def initialize_position
    return if position_came_from_user?

    last_step = playbook.steps.order(:position).last
    self.position = last_step ? last_step.position + 1 : 0
  end
end

app/controllers/steps_controller.rb
class StepsController < ProtectedController
  before_action :set_playbook, only: [:index, :show, :create]
  before_action :set_step, only: [:show, :edit, :update, :destroy]

  # GET /steps or /steps.json
  def index
    @steps = policy_scope(Step).where(playbook_id: params[:playbook_id])
  end

  # GET /steps/1 or /steps/1.json
  def show; end

  # GET /steps/new
  def new
    @step = Step.new
  end

  # GET /steps/1/edit
  def edit; end

  # POST /steps or /steps.json
  def create # rubocop:disable Metrics/AbcSize
    @step = Step.new(step_params)
    @step.playbook = @playbook

    respond_to do |format|
      if @step.save
        format.html { redirect_to playbook_url(@step.playbook), notice: I18n.t('controller.step.create.success') }
        format.json { render :show, status: :created, location: @step }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1 or /steps/1.json
  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to playbook_url(@step.playbook), notice: I18n.t('controller.step.update.success') }
        format.json { render :show, status: :ok, location: @step }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1 or /steps/1.json
  def destroy
    @step.destroy!

    respond_to do |format|
      format.html { redirect_to playbook_url(@step.playbook), notice: I18n.t('controller.step.destroy.success') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_step
    @step = Step.find(params[:id])

    authorize @step
  end

  def set_playbook
    @playbook = Playbook.find(params[:playbook_id])

    authorize @playbook
  end

  # Only allow a list of trusted parameters through.
  def step_params
    params.require(:step).permit(:name, :content, :position)
  end
end

app/views/steps/_form.html.erb
<% form_url = step.id ? step_url(step) : playbook_steps_url(playbook_id: params[:playbook_id]) %>
<%= form_with(model: step, url: form_url) do |form| %>
  <% if step.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(step.errors.count, 'error') %> prohibited this step from being saved:</h2>

      <ul>
        <% step.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: 'display: block' %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :content, style: 'display: block' %>
    <%= form.text_area :content %>
  </div>

  <% if step.id %>
  <div>
    <%= form.label :position, style: 'display: block' %>
    <%= form.number_field :position %>
  </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/steps/_step.html.erb
<div id="<%= dom_id step %>">
  <p>
    <strong>Playbook:</strong>
    <%= step.playbook_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= step.name %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= step.content %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= step.position %>
  </p>

</div>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form', step: @step %>

<br>

<div>
  <%= link_to 'Show this step', playbook_step_path(@step.playbook, @step) %> |
  <%= link_to 'Back to steps', playbook_steps_path(@step.playbook) %>
</div>

app/views/steps/index.html.erb
<h1>Steps</h1>
<p>For playbook: <%= link_to @playbook.name, playbook_url(@playbook) %></p>

<div id="steps">
  <% @steps.each do |step| %>
    <%= render step %>
    <p>
      <%= link_to 'Show this step', playbook_step_path(step.playbook, step) %>
    </p>
  <% end %>
</div>

<%= link_to 'New step', new_playbook_step_path %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form', step: @step %>

<br>

<div>
  <%= link_to 'Back to steps', playbook_steps_path(playbook_id: params[:playbook_id]) %>
</div>

app/views/steps/show.html.erb
<%= render @step %>

<div>
  <%= link_to 'Edit this step', edit_playbook_step_path(@step) %> |
  <%= link_to 'Back to steps', playbook_steps_path %>

  <%= button_to 'Destroy this step', @step, method: :delete %>
</div>